name: Poi
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - IPy
  - ipydatetime
  - ipykernel
  - ipython
  - ipywidgets
  - ninja
  - numpy=1.22
  - pandas=1.4
  - Pillow=9.2
  - scipy=1.11
  - tensorflow=2.9
  - tensorflow-probability=0.17
  - torchvision=0.13
  - tqdm=4.64
  - pip:
    - torch==1.12
    - tensorflow_datasets==4.5
    - tensorflow_gan==2.0
    - tensorflow_hub==0.12
    - jupyter-client
    - jupyter-console
    - jupyter-contrib-core
    - jupyter-contrib-nbextensions
    - jupyter-core
    - jupyter-highlight-selected-word
    - jupyter-latex-envs
    - jupyter-nbextensions-configurator
    - jupyter-server
    - jupyter-server-mathjax
    - jupyter-telemetry
    - jupyterhub
    - jupyterlab
    - jupyterlab-git
    - jupyterlab-pygments
    - jupyterlab-server
    - jupyterlab-widgets
    - ipython-genutils
    - absl-py==1.2
    - jax==0.4
    - jaxlib==0.4
    - ml_collections==0.1
    - requests==2.27
    - six==1.15